// <auto-generated />
using System;
using Microservicio_Persona.AccessData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microservicio_Persona.AccessData.Migrations
{
    [DbContext(typeof(DbContexto))]
    [Migration("20200921020709_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microservicio_Persona.Domain.Entities.Especialidad", b =>
                {
                    b.Property<int>("EspecialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspecialidadId");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("Microservicio_Persona.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("EstudianteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Legajo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteID");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("Microservicio_Persona.Domain.Entities.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EspecialidadNavegatorEspecialidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfesorId");

                    b.HasIndex("EspecialidadNavegatorEspecialidadId");

                    b.ToTable("Profesor");

                    b.HasData(
                        new
                        {
                            ProfesorId = 1,
                            Apellido = "olivera",
                            Email = "lolivera.unaj@gmail.com>",
                            Especialidad = "Programacion",
                            Nombre = "lucas"
                        },
                        new
                        {
                            ProfesorId = 2,
                            Apellido = "conde",
                            Email = "sergiounaj@gmail.com>",
                            Especialidad = "Documentacion",
                            Nombre = "sergio"
                        },
                        new
                        {
                            ProfesorId = 3,
                            Apellido = "jorge",
                            Email = "octaviojorge37@gmail.com>",
                            Especialidad = "Programacion orientada a objetos",
                            Nombre = "octavio"
                        },
                        new
                        {
                            ProfesorId = 4,
                            Apellido = "Amet",
                            Email = "leonardoAmet@gmail.com>",
                            Especialidad = "complejidad temporal",
                            Nombre = "leonardo"
                        });
                });

            modelBuilder.Entity("Microservicio_Persona.Domain.Entities.Profesor", b =>
                {
                    b.HasOne("Microservicio_Persona.Domain.Entities.Especialidad", "EspecialidadNavegator")
                        .WithMany()
                        .HasForeignKey("EspecialidadNavegatorEspecialidadId");
                });
#pragma warning restore 612, 618
        }
    }
}
