// <auto-generated />
using Microservicio_Persona.AccessData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microservicio_Persona.AccessData.Migrations
{
    [DbContext(typeof(DbContexto))]
    partial class DbContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microservicio_Persona.Domain.Entities.Especialidad", b =>
                {
                    b.Property<int>("EspecialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspecialidadId");

                    b.ToTable("Especialidad");

                    b.HasData(
                        new
                        {
                            EspecialidadId = 1,
                            Descripcion = "Programacion"
                        },
                        new
                        {
                            EspecialidadId = 2,
                            Descripcion = "Documentacion"
                        },
                        new
                        {
                            EspecialidadId = 3,
                            Descripcion = "Matematica"
                        },
                        new
                        {
                            EspecialidadId = 4,
                            Descripcion = "Base de datos"
                        },
                        new
                        {
                            EspecialidadId = 5,
                            Descripcion = "Idioma"
                        },
                        new
                        {
                            EspecialidadId = 6,
                            Descripcion = "Tecnico"
                        });
                });

            modelBuilder.Entity("Microservicio_Persona.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("EstudianteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Legajo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EstudianteID");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("Microservicio_Persona.Domain.Entities.EstudianteCurso", b =>
                {
                    b.Property<int>("EstudianteCursoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CursoID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstudianteID")
                        .HasColumnType("int");

                    b.HasKey("EstudianteCursoID");

                    b.HasIndex("EstudianteID");

                    b.ToTable("EstudianteCurso");
                });

            modelBuilder.Entity("Microservicio_Persona.Domain.Entities.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProfesorId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("Profesor");

                    b.HasData(
                        new
                        {
                            ProfesorId = 1,
                            Apellido = "Olivera",
                            Email = "lolivera.unaj@gmail.com",
                            EspecialidadId = 1,
                            Nombre = "Lucas",
                            UsuarioId = 20
                        },
                        new
                        {
                            ProfesorId = 2,
                            Apellido = "Conde",
                            Email = "sergiounaj@gmail.com",
                            EspecialidadId = 2,
                            Nombre = "Sergio",
                            UsuarioId = 21
                        },
                        new
                        {
                            ProfesorId = 3,
                            Apellido = "Jorge",
                            Email = "octaviojorge37@gmail.com",
                            EspecialidadId = 1,
                            Nombre = "Octavio",
                            UsuarioId = 22
                        },
                        new
                        {
                            ProfesorId = 4,
                            Apellido = "Amet",
                            Email = "leonardoAmet@gmail.com",
                            EspecialidadId = 1,
                            Nombre = "Leonardo",
                            UsuarioId = 23
                        },
                        new
                        {
                            ProfesorId = 5,
                            Apellido = "Osio",
                            Email = "jorgeosio@gmail.com",
                            EspecialidadId = 1,
                            Nombre = "Jorge",
                            UsuarioId = 24
                        },
                        new
                        {
                            ProfesorId = 6,
                            Apellido = "Rosa",
                            Email = "mariarosa@gmail.com",
                            EspecialidadId = 5,
                            Nombre = "Maria",
                            UsuarioId = 25
                        });
                });

            modelBuilder.Entity("Microservicio_Persona.Domain.Entities.EstudianteCurso", b =>
                {
                    b.HasOne("Microservicio_Persona.Domain.Entities.Estudiante", "EstudianteNavegador")
                        .WithMany("EstudianteCursoNavegacion")
                        .HasForeignKey("EstudianteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microservicio_Persona.Domain.Entities.Profesor", b =>
                {
                    b.HasOne("Microservicio_Persona.Domain.Entities.Especialidad", "EspecialidadNavegator")
                        .WithMany("Profesor")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
